AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket using a default parameter

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket
    Default: yaswanth-demo-s3-bucket-7144  # Replace with a unique bucket name

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Environment
          Value: Dev
        - Key: CreatedBy
          Value: CloudFormation

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref MyS3Bucket
